version: '3.7'
services:

    postgres:
        image: postgres:latest
        container_name: postgres
        environment:
            - POSTGRES_USER=<username>
            - POSTGRES_PASSWORD=<password>
            - POSTGRES_HOST_AUTH_METHOD=trust
        ports:
            - "5432:5432"
        volumes:
            - ./tmp/postgres:/var/lib/postgresql/data
            - ./sql/:/docker-entrypoint-initdb.d

    elasticsearch:
        image: elasticsearch:7.9.3
        container_name: elasticsearch
        networks:
            - local
        ports:
            - "9200:9200"
        environment:
            - "discovery.type=single-node"
        volumes:
            - ./tmp/elasticsearch:/usr/share/elasticsearch/data

    kibana:
        image: kibana:7.9.3
        container_name: kibana
        environment:
        - "ELASTICSEARCH_URL=http://elasticsearch:9200"
        ports:
        - "5601:5601"
        networks:
        - local
        depends_on:
        - elasticsearch

    redis:
        image: redis:5.0-alpine
        container_name: redis
        ports:
            - "6379:6379"
        volumes:
            - ./tmp/redis:/data

    rabbitmq:
        image: rabbitmq:latest
        container_name: 'rabbitmq'
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ./tmp/rabbitmq/data/:/var/lib/rabbitmq/
            - ./tmp/rabbitmq/log/:/var/log/rabbitmq
        networks:
            - local  

    minio:
        image: quay.io/minio/minio:latest
        container_name: 'minio'
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: <username>
            MINIO_ROOT_PASSWORD: <password>

networks:
    local:
        driver: bridge

